<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerATYP6Dt\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerATYP6Dt/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerATYP6Dt.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerATYP6Dt\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerATYP6Dt\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ATYP6Dt',
    'container.build_id' => '4bfef4a8',
    'container.build_time' => 1571205411,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerATYP6Dt');
